const FbxImplementation* GetImplementation( const FbxObject* pObject, const char * pImplementationTarget );

/*
template <typename T> bool GetBoundPropertyValue(FbxBindingTable const* pBindingTable,
                                                 char const* pEntryName, 
                                                 FbxImplementation const* pImplementation,
                                                 FbxObject const* pBoundObject,
                                                 T& pValue)
*/